name: "Build"
on:
  workflow_dispatch:
jobs:
  build:
    name: "Build" 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t caching-test .
      - run: docker run --rm caching-test